version: "3"
services:
  nginx:
    build: ./
    volumes:
    - "./apicaddy-cert.pem:/etc/nginx/apicaddy-cert.pem"
    - "./apicaddy-key.pem:/etc/nginx/apicaddy-key.pem"
    - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - "443:443"